version: 2
jobs:
  build:
    docker:
      - image: circleci/python
    environment:
      ASSUME_ROLE_ARN: arn:aws:iam::${AWS_ACCOUNT_ID}:role/CodeCommitPushAccess
      CODECOMMIT_URL: https://git-codecommit.${AWS_DEFAULT_REGION}.amazonaws.com/v1/repos/${ECR_REPOSITORY_NAME}
      CODECOMMIT_USER_NAME: ${CODECOMMIT_USER_NAME}
      CODECOMMIT_USER_PASSWORD: ${CODECOMMIT_USER_PASSWORD}
    steps:
      - checkout
      - run: sudo pip install awscli
      - run:
          name: Push to CodeCommit
          command: |
            export AWS_ACCESS_KEY_ID="${AWS_ACCESS_KEY_ID}"
            export AWS_SECRET_ACCESS_KEY="${AWS_SECRET_ACCESS_KEY}"
            git config credential.helper '!aws codecommit credential-helper $@'
            git config credential.useHttpPath true
            git push $CODECOMMIT_URL master
workflows:
  version: 2
  build:
    jobs:
      - build
